//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.31 at 08:56:32 PM PDT 
//


package com.jdkoftinoff.jdksavdecc.aemxml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * See IEEE Std 1722.1-2013 Clause 7.2.13
 * 
 * <p>Java class for AudioStreamPortDescriptor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AudioStreamPortDescriptor">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="clock_domain_index" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}DescriptorIndex"/>
 *         &lt;element name="port_flags" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Doublet"/>
 *         &lt;element name="controls" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}ControlDescriptors" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="clusters" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}AudioClusterDescriptors"/>
 *         &lt;element name="maps" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}AudioMapDescriptors" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="symbol" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AudioStreamPortDescriptor", propOrder = {
    "clockDomainIndex",
    "portFlags",
    "controls",
    "clusters",
    "maps"
})
public class AudioStreamPortDescriptor {

    @XmlElement(name = "clock_domain_index", required = true)
    protected String clockDomainIndex;
    @XmlElement(name = "port_flags", required = true)
    protected String portFlags;
    protected List<ControlDescriptors> controls;
    @XmlElement(required = true)
    protected AudioClusterDescriptors clusters;
    protected List<AudioMapDescriptors> maps;
    @XmlAttribute(name = "symbol")
    protected String symbol;

    /**
     * Gets the value of the clockDomainIndex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClockDomainIndex() {
        return clockDomainIndex;
    }

    /**
     * Sets the value of the clockDomainIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClockDomainIndex(String value) {
        this.clockDomainIndex = value;
    }

    /**
     * Gets the value of the portFlags property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPortFlags() {
        return portFlags;
    }

    /**
     * Sets the value of the portFlags property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPortFlags(String value) {
        this.portFlags = value;
    }

    /**
     * Gets the value of the controls property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the controls property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getControls().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ControlDescriptors }
     * 
     * 
     */
    public List<ControlDescriptors> getControls() {
        if (controls == null) {
            controls = new ArrayList<ControlDescriptors>();
        }
        return this.controls;
    }

    /**
     * Gets the value of the clusters property.
     * 
     * @return
     *     possible object is
     *     {@link AudioClusterDescriptors }
     *     
     */
    public AudioClusterDescriptors getClusters() {
        return clusters;
    }

    /**
     * Sets the value of the clusters property.
     * 
     * @param value
     *     allowed object is
     *     {@link AudioClusterDescriptors }
     *     
     */
    public void setClusters(AudioClusterDescriptors value) {
        this.clusters = value;
    }

    /**
     * Gets the value of the maps property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the maps property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMaps().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AudioMapDescriptors }
     * 
     * 
     */
    public List<AudioMapDescriptors> getMaps() {
        if (maps == null) {
            maps = new ArrayList<AudioMapDescriptors>();
        }
        return this.maps;
    }

    /**
     * Gets the value of the symbol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * Sets the value of the symbol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSymbol(String value) {
        this.symbol = value;
    }

}
