//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.31 at 08:56:32 PM PDT 
//


package com.jdkoftinoff.jdksavdecc.aemxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * See IEEE Std 1722.1-2013 Clause 7.2.8
 * 
 * <p>Java class for AVBInterfaceDescriptor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AVBInterfaceDescriptor">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="object_name" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}AVDECCString" minOccurs="0"/>
 *         &lt;element name="localized_description" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}LocalizedStringContainer"/>
 *         &lt;element name="mac_address" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}MAC"/>
 *         &lt;element name="clock_identity" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}EUI64"/>
 *         &lt;element name="interface_flags" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Doublet"/>
 *         &lt;element name="priority1" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Octet"/>
 *         &lt;element name="clock_class" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Octet"/>
 *         &lt;element name="offset_scaled_log_variance" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Doublet"/>
 *         &lt;element name="clock_accuracy" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Octet"/>
 *         &lt;element name="priority2" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Octet"/>
 *         &lt;element name="domain_number" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Octet"/>
 *         &lt;element name="log_sync_interval" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Octet"/>
 *         &lt;element name="log_announce_interval" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Octet"/>
 *         &lt;element name="log_pdelay_interval" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Octet"/>
 *         &lt;element name="port_number" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Doublet"/>
 *       &lt;/sequence>
 *       &lt;attribute name="symbol" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AVBInterfaceDescriptor", propOrder = {
    "objectName",
    "localizedDescription",
    "macAddress",
    "clockIdentity",
    "interfaceFlags",
    "priority1",
    "clockClass",
    "offsetScaledLogVariance",
    "clockAccuracy",
    "priority2",
    "domainNumber",
    "logSyncInterval",
    "logAnnounceInterval",
    "logPdelayInterval",
    "portNumber"
})
public class AVBInterfaceDescriptor {

    @XmlElement(name = "object_name")
    protected String objectName;
    @XmlElement(name = "localized_description", required = true)
    protected LocalizedStringContainer localizedDescription;
    @XmlElement(name = "mac_address", required = true)
    protected String macAddress;
    @XmlElement(name = "clock_identity", required = true)
    protected String clockIdentity;
    @XmlElement(name = "interface_flags", required = true)
    protected String interfaceFlags;
    @XmlElement(required = true)
    protected String priority1;
    @XmlElement(name = "clock_class", required = true)
    protected String clockClass;
    @XmlElement(name = "offset_scaled_log_variance", required = true)
    protected String offsetScaledLogVariance;
    @XmlElement(name = "clock_accuracy", required = true)
    protected String clockAccuracy;
    @XmlElement(required = true)
    protected String priority2;
    @XmlElement(name = "domain_number", required = true)
    protected String domainNumber;
    @XmlElement(name = "log_sync_interval", required = true)
    protected String logSyncInterval;
    @XmlElement(name = "log_announce_interval", required = true)
    protected String logAnnounceInterval;
    @XmlElement(name = "log_pdelay_interval", required = true)
    protected String logPdelayInterval;
    @XmlElement(name = "port_number", required = true)
    protected String portNumber;
    @XmlAttribute(name = "symbol")
    protected String symbol;

    /**
     * Gets the value of the objectName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjectName() {
        return objectName;
    }

    /**
     * Sets the value of the objectName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjectName(String value) {
        this.objectName = value;
    }

    /**
     * Gets the value of the localizedDescription property.
     * 
     * @return
     *     possible object is
     *     {@link LocalizedStringContainer }
     *     
     */
    public LocalizedStringContainer getLocalizedDescription() {
        return localizedDescription;
    }

    /**
     * Sets the value of the localizedDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocalizedStringContainer }
     *     
     */
    public void setLocalizedDescription(LocalizedStringContainer value) {
        this.localizedDescription = value;
    }

    /**
     * Gets the value of the macAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMacAddress() {
        return macAddress;
    }

    /**
     * Sets the value of the macAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMacAddress(String value) {
        this.macAddress = value;
    }

    /**
     * Gets the value of the clockIdentity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClockIdentity() {
        return clockIdentity;
    }

    /**
     * Sets the value of the clockIdentity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClockIdentity(String value) {
        this.clockIdentity = value;
    }

    /**
     * Gets the value of the interfaceFlags property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterfaceFlags() {
        return interfaceFlags;
    }

    /**
     * Sets the value of the interfaceFlags property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterfaceFlags(String value) {
        this.interfaceFlags = value;
    }

    /**
     * Gets the value of the priority1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriority1() {
        return priority1;
    }

    /**
     * Sets the value of the priority1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriority1(String value) {
        this.priority1 = value;
    }

    /**
     * Gets the value of the clockClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClockClass() {
        return clockClass;
    }

    /**
     * Sets the value of the clockClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClockClass(String value) {
        this.clockClass = value;
    }

    /**
     * Gets the value of the offsetScaledLogVariance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOffsetScaledLogVariance() {
        return offsetScaledLogVariance;
    }

    /**
     * Sets the value of the offsetScaledLogVariance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOffsetScaledLogVariance(String value) {
        this.offsetScaledLogVariance = value;
    }

    /**
     * Gets the value of the clockAccuracy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClockAccuracy() {
        return clockAccuracy;
    }

    /**
     * Sets the value of the clockAccuracy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClockAccuracy(String value) {
        this.clockAccuracy = value;
    }

    /**
     * Gets the value of the priority2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriority2() {
        return priority2;
    }

    /**
     * Sets the value of the priority2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriority2(String value) {
        this.priority2 = value;
    }

    /**
     * Gets the value of the domainNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDomainNumber() {
        return domainNumber;
    }

    /**
     * Sets the value of the domainNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDomainNumber(String value) {
        this.domainNumber = value;
    }

    /**
     * Gets the value of the logSyncInterval property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogSyncInterval() {
        return logSyncInterval;
    }

    /**
     * Sets the value of the logSyncInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogSyncInterval(String value) {
        this.logSyncInterval = value;
    }

    /**
     * Gets the value of the logAnnounceInterval property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogAnnounceInterval() {
        return logAnnounceInterval;
    }

    /**
     * Sets the value of the logAnnounceInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogAnnounceInterval(String value) {
        this.logAnnounceInterval = value;
    }

    /**
     * Gets the value of the logPdelayInterval property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogPdelayInterval() {
        return logPdelayInterval;
    }

    /**
     * Sets the value of the logPdelayInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogPdelayInterval(String value) {
        this.logPdelayInterval = value;
    }

    /**
     * Gets the value of the portNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPortNumber() {
        return portNumber;
    }

    /**
     * Sets the value of the portNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPortNumber(String value) {
        this.portNumber = value;
    }

    /**
     * Gets the value of the symbol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * Sets the value of the symbol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSymbol(String value) {
        this.symbol = value;
    }

}
