//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.31 at 08:56:32 PM PDT 
//


package com.jdkoftinoff.jdksavdecc.aemxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BodePlotPoint complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BodePlotPoint">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bode_plot" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}BodePlot"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BodePlotPoint", propOrder = {
    "bodePlot"
})
public class BodePlotPoint {

    @XmlElement(name = "bode_plot", required = true)
    protected BodePlot bodePlot;

    /**
     * Gets the value of the bodePlot property.
     * 
     * @return
     *     possible object is
     *     {@link BodePlot }
     *     
     */
    public BodePlot getBodePlot() {
        return bodePlot;
    }

    /**
     * Sets the value of the bodePlot property.
     * 
     * @param value
     *     allowed object is
     *     {@link BodePlot }
     *     
     */
    public void setBodePlot(BodePlot value) {
        this.bodePlot = value;
    }

}
