//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.31 at 08:56:32 PM PDT 
//


package com.jdkoftinoff.jdksavdecc.aemxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * See IEEE Std 1722.1-2013 Clause 7.2.9
 * 
 * <p>Java class for ClockSourceDescriptor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClockSourceDescriptor">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="object_name" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}AVDECCString" minOccurs="0"/>
 *         &lt;element name="localized_description" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}LocalizedStringContainer"/>
 *         &lt;element name="clock_source_flags" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Doublet"/>
 *         &lt;element name="clock_source_type" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Doublet"/>
 *         &lt;element name="clock_source_id" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}EUI64"/>
 *         &lt;element name="clock_source_location_type" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}DescriptorType"/>
 *         &lt;element name="clock_source_location_index" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}DescriptorIndex"/>
 *       &lt;/sequence>
 *       &lt;attribute name="symbol" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClockSourceDescriptor", propOrder = {
    "objectName",
    "localizedDescription",
    "clockSourceFlags",
    "clockSourceType",
    "clockSourceId",
    "clockSourceLocationType",
    "clockSourceLocationIndex"
})
public class ClockSourceDescriptor {

    @XmlElement(name = "object_name")
    protected String objectName;
    @XmlElement(name = "localized_description", required = true)
    protected LocalizedStringContainer localizedDescription;
    @XmlElement(name = "clock_source_flags", required = true)
    protected String clockSourceFlags;
    @XmlElement(name = "clock_source_type", required = true)
    protected String clockSourceType;
    @XmlElement(name = "clock_source_id", required = true)
    protected String clockSourceId;
    @XmlElement(name = "clock_source_location_type", required = true)
    protected String clockSourceLocationType;
    @XmlElement(name = "clock_source_location_index", required = true)
    protected String clockSourceLocationIndex;
    @XmlAttribute(name = "symbol")
    protected String symbol;

    /**
     * Gets the value of the objectName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjectName() {
        return objectName;
    }

    /**
     * Sets the value of the objectName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjectName(String value) {
        this.objectName = value;
    }

    /**
     * Gets the value of the localizedDescription property.
     * 
     * @return
     *     possible object is
     *     {@link LocalizedStringContainer }
     *     
     */
    public LocalizedStringContainer getLocalizedDescription() {
        return localizedDescription;
    }

    /**
     * Sets the value of the localizedDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocalizedStringContainer }
     *     
     */
    public void setLocalizedDescription(LocalizedStringContainer value) {
        this.localizedDescription = value;
    }

    /**
     * Gets the value of the clockSourceFlags property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClockSourceFlags() {
        return clockSourceFlags;
    }

    /**
     * Sets the value of the clockSourceFlags property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClockSourceFlags(String value) {
        this.clockSourceFlags = value;
    }

    /**
     * Gets the value of the clockSourceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClockSourceType() {
        return clockSourceType;
    }

    /**
     * Sets the value of the clockSourceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClockSourceType(String value) {
        this.clockSourceType = value;
    }

    /**
     * Gets the value of the clockSourceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClockSourceId() {
        return clockSourceId;
    }

    /**
     * Sets the value of the clockSourceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClockSourceId(String value) {
        this.clockSourceId = value;
    }

    /**
     * Gets the value of the clockSourceLocationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClockSourceLocationType() {
        return clockSourceLocationType;
    }

    /**
     * Sets the value of the clockSourceLocationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClockSourceLocationType(String value) {
        this.clockSourceLocationType = value;
    }

    /**
     * Gets the value of the clockSourceLocationIndex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClockSourceLocationIndex() {
        return clockSourceLocationIndex;
    }

    /**
     * Sets the value of the clockSourceLocationIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClockSourceLocationIndex(String value) {
        this.clockSourceLocationIndex = value;
    }

    /**
     * Gets the value of the symbol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * Sets the value of the symbol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSymbol(String value) {
        this.symbol = value;
    }

}
