//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.31 at 08:56:32 PM PDT 
//


package com.jdkoftinoff.jdksavdecc.aemxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * See IEEE Std 1722.1-2013 Clause 7.2.11
 * 
 * <p>Java class for LocaleDescriptor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LocaleDescriptor">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="locale_identifier" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}AVDECCString"/>
 *         &lt;element name="locale_strings" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}StringsDescriptors"/>
 *       &lt;/sequence>
 *       &lt;attribute name="symbol" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LocaleDescriptor", propOrder = {
    "localeIdentifier",
    "localeStrings"
})
public class LocaleDescriptor {

    @XmlElement(name = "locale_identifier", required = true)
    protected String localeIdentifier;
    @XmlElement(name = "locale_strings", required = true)
    protected StringsDescriptors localeStrings;
    @XmlAttribute(name = "symbol")
    protected String symbol;

    /**
     * Gets the value of the localeIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocaleIdentifier() {
        return localeIdentifier;
    }

    /**
     * Sets the value of the localeIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocaleIdentifier(String value) {
        this.localeIdentifier = value;
    }

    /**
     * Gets the value of the localeStrings property.
     * 
     * @return
     *     possible object is
     *     {@link StringsDescriptors }
     *     
     */
    public StringsDescriptors getLocaleStrings() {
        return localeStrings;
    }

    /**
     * Sets the value of the localeStrings property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringsDescriptors }
     *     
     */
    public void setLocaleStrings(StringsDescriptors value) {
        this.localeStrings = value;
    }

    /**
     * Gets the value of the symbol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * Sets the value of the symbol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSymbol(String value) {
        this.symbol = value;
    }

}
