//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.31 at 08:56:32 PM PDT 
//


package com.jdkoftinoff.jdksavdecc.aemxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * See IEEE Std 1722.1-2013 Clause 7.2.10
 * 
 * <p>Java class for MemoryObjectDescriptor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MemoryObjectDescriptor">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="object_name" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}AVDECCString" minOccurs="0"/>
 *         &lt;element name="localized_description" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}LocalizedStringContainer"/>
 *         &lt;element name="memory_object_type" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Doublet"/>
 *         &lt;element name="target_descriptor_type" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}DescriptorType"/>
 *         &lt;element name="target_descriptor_index" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}DescriptorIndex"/>
 *         &lt;element name="start_address" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Octlet"/>
 *         &lt;element name="maximum_length" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Octlet"/>
 *         &lt;element name="length" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Octlet"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="data_url" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *           &lt;element name="data" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}HexBlobData"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="symbol" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MemoryObjectDescriptor", propOrder = {
    "objectName",
    "localizedDescription",
    "memoryObjectType",
    "targetDescriptorType",
    "targetDescriptorIndex",
    "startAddress",
    "maximumLength",
    "length",
    "dataUrl",
    "data"
})
public class MemoryObjectDescriptor {

    @XmlElement(name = "object_name")
    protected String objectName;
    @XmlElement(name = "localized_description", required = true)
    protected LocalizedStringContainer localizedDescription;
    @XmlElement(name = "memory_object_type", required = true)
    protected String memoryObjectType;
    @XmlElement(name = "target_descriptor_type", required = true)
    protected String targetDescriptorType;
    @XmlElement(name = "target_descriptor_index", required = true)
    protected String targetDescriptorIndex;
    @XmlElement(name = "start_address", required = true)
    protected String startAddress;
    @XmlElement(name = "maximum_length", required = true)
    protected String maximumLength;
    @XmlElement(required = true)
    protected String length;
    @XmlElement(name = "data_url")
    @XmlSchemaType(name = "anyURI")
    protected String dataUrl;
    protected String data;
    @XmlAttribute(name = "symbol")
    protected String symbol;

    /**
     * Gets the value of the objectName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjectName() {
        return objectName;
    }

    /**
     * Sets the value of the objectName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjectName(String value) {
        this.objectName = value;
    }

    /**
     * Gets the value of the localizedDescription property.
     * 
     * @return
     *     possible object is
     *     {@link LocalizedStringContainer }
     *     
     */
    public LocalizedStringContainer getLocalizedDescription() {
        return localizedDescription;
    }

    /**
     * Sets the value of the localizedDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocalizedStringContainer }
     *     
     */
    public void setLocalizedDescription(LocalizedStringContainer value) {
        this.localizedDescription = value;
    }

    /**
     * Gets the value of the memoryObjectType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemoryObjectType() {
        return memoryObjectType;
    }

    /**
     * Sets the value of the memoryObjectType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemoryObjectType(String value) {
        this.memoryObjectType = value;
    }

    /**
     * Gets the value of the targetDescriptorType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetDescriptorType() {
        return targetDescriptorType;
    }

    /**
     * Sets the value of the targetDescriptorType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetDescriptorType(String value) {
        this.targetDescriptorType = value;
    }

    /**
     * Gets the value of the targetDescriptorIndex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetDescriptorIndex() {
        return targetDescriptorIndex;
    }

    /**
     * Sets the value of the targetDescriptorIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetDescriptorIndex(String value) {
        this.targetDescriptorIndex = value;
    }

    /**
     * Gets the value of the startAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartAddress() {
        return startAddress;
    }

    /**
     * Sets the value of the startAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartAddress(String value) {
        this.startAddress = value;
    }

    /**
     * Gets the value of the maximumLength property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaximumLength() {
        return maximumLength;
    }

    /**
     * Sets the value of the maximumLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaximumLength(String value) {
        this.maximumLength = value;
    }

    /**
     * Gets the value of the length property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLength(String value) {
        this.length = value;
    }

    /**
     * Gets the value of the dataUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataUrl() {
        return dataUrl;
    }

    /**
     * Sets the value of the dataUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataUrl(String value) {
        this.dataUrl = value;
    }

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setData(String value) {
        this.data = value;
    }

    /**
     * Gets the value of the symbol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * Sets the value of the symbol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSymbol(String value) {
        this.symbol = value;
    }

}
