//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.31 at 08:56:32 PM PDT 
//


package com.jdkoftinoff.jdksavdecc.aemxml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.jdkoftinoff.jdksavdecc.aemxml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Entity_QNAME = new QName("http://grouper.ieee.org/groups/1722/1/contributions/xml", "entity");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.jdkoftinoff.jdksavdecc.aemxml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EntityV1 }
     * 
     */
    public EntityV1 createEntityV1() {
        return new EntityV1();
    }

    /**
     * Create an instance of {@link T001A }
     * 
     */
    public T001A createT001A() {
        return new T001A();
    }

    /**
     * Create an instance of {@link T001B }
     * 
     */
    public T001B createT001B() {
        return new T001B();
    }

    /**
     * Create an instance of {@link T001C }
     * 
     */
    public T001C createT001C() {
        return new T001C();
    }

    /**
     * Create an instance of {@link InternalPortDescriptors }
     * 
     */
    public InternalPortDescriptors createInternalPortDescriptors() {
        return new InternalPortDescriptors();
    }

    /**
     * Create an instance of {@link T001D }
     * 
     */
    public T001D createT001D() {
        return new T001D();
    }

    /**
     * Create an instance of {@link TUNKNOWN }
     * 
     */
    public TUNKNOWN createTUNKNOWN() {
        return new TUNKNOWN();
    }

    /**
     * Create an instance of {@link SensorUnitDescriptors }
     * 
     */
    public SensorUnitDescriptors createSensorUnitDescriptors() {
        return new SensorUnitDescriptors();
    }

    /**
     * Create an instance of {@link T001E }
     * 
     */
    public T001E createT001E() {
        return new T001E();
    }

    /**
     * Create an instance of {@link T001F }
     * 
     */
    public T001F createT001F() {
        return new T001F();
    }

    /**
     * Create an instance of {@link VideoMapDescriptors }
     * 
     */
    public VideoMapDescriptors createVideoMapDescriptors() {
        return new VideoMapDescriptors();
    }

    /**
     * Create an instance of {@link SignalSelectorDescriptors }
     * 
     */
    public SignalSelectorDescriptors createSignalSelectorDescriptors() {
        return new SignalSelectorDescriptors();
    }

    /**
     * Create an instance of {@link ControlDescriptors }
     * 
     */
    public ControlDescriptors createControlDescriptors() {
        return new ControlDescriptors();
    }

    /**
     * Create an instance of {@link SensorStreamPortDescriptors }
     * 
     */
    public SensorStreamPortDescriptors createSensorStreamPortDescriptors() {
        return new SensorStreamPortDescriptors();
    }

    /**
     * Create an instance of {@link AudioStreamPortDescriptor }
     * 
     */
    public AudioStreamPortDescriptor createAudioStreamPortDescriptor() {
        return new AudioStreamPortDescriptor();
    }

    /**
     * Create an instance of {@link Values }
     * 
     */
    public Values createValues() {
        return new Values();
    }

    /**
     * Create an instance of {@link T000B }
     * 
     */
    public T000B createT000B() {
        return new T000B();
    }

    /**
     * Create an instance of {@link T000C }
     * 
     */
    public T000C createT000C() {
        return new T000C();
    }

    /**
     * Create an instance of {@link T000A }
     * 
     */
    public T000A createT000A() {
        return new T000A();
    }

    /**
     * Create an instance of {@link SensorClusterDescriptors }
     * 
     */
    public SensorClusterDescriptors createSensorClusterDescriptors() {
        return new SensorClusterDescriptors();
    }

    /**
     * Create an instance of {@link SamplingRates }
     * 
     */
    public SamplingRates createSamplingRates() {
        return new SamplingRates();
    }

    /**
     * Create an instance of {@link ClockDomainDescriptor }
     * 
     */
    public ClockDomainDescriptor createClockDomainDescriptor() {
        return new ClockDomainDescriptor();
    }

    /**
     * Create an instance of {@link SignalDemultiplexerDescriptors }
     * 
     */
    public SignalDemultiplexerDescriptors createSignalDemultiplexerDescriptors() {
        return new SignalDemultiplexerDescriptors();
    }

    /**
     * Create an instance of {@link T000F }
     * 
     */
    public T000F createT000F() {
        return new T000F();
    }

    /**
     * Create an instance of {@link SensorUnitDescriptor }
     * 
     */
    public SensorUnitDescriptor createSensorUnitDescriptor() {
        return new SensorUnitDescriptor();
    }

    /**
     * Create an instance of {@link T000D }
     * 
     */
    public T000D createT000D() {
        return new T000D();
    }

    /**
     * Create an instance of {@link T000E }
     * 
     */
    public T000E createT000E() {
        return new T000E();
    }

    /**
     * Create an instance of {@link LocaleDescriptors }
     * 
     */
    public LocaleDescriptors createLocaleDescriptors() {
        return new LocaleDescriptors();
    }

    /**
     * Create an instance of {@link T0023 }
     * 
     */
    public T0023 createT0023() {
        return new T0023();
    }

    /**
     * Create an instance of {@link T0022 }
     * 
     */
    public T0022 createT0022() {
        return new T0022();
    }

    /**
     * Create an instance of {@link T0021 }
     * 
     */
    public T0021 createT0021() {
        return new T0021();
    }

    /**
     * Create an instance of {@link T0020 }
     * 
     */
    public T0020 createT0020() {
        return new T0020();
    }

    /**
     * Create an instance of {@link VideoClusterDescriptors }
     * 
     */
    public VideoClusterDescriptors createVideoClusterDescriptors() {
        return new VideoClusterDescriptors();
    }

    /**
     * Create an instance of {@link MemoryObjectDescriptors }
     * 
     */
    public MemoryObjectDescriptors createMemoryObjectDescriptors() {
        return new MemoryObjectDescriptors();
    }

    /**
     * Create an instance of {@link UnsignedQuadletOptions }
     * 
     */
    public UnsignedQuadletOptions createUnsignedQuadletOptions() {
        return new UnsignedQuadletOptions();
    }

    /**
     * Create an instance of {@link SignalMultiplexerDescriptors }
     * 
     */
    public SignalMultiplexerDescriptors createSignalMultiplexerDescriptors() {
        return new SignalMultiplexerDescriptors();
    }

    /**
     * Create an instance of {@link SensorMapDescriptors }
     * 
     */
    public SensorMapDescriptors createSensorMapDescriptors() {
        return new SensorMapDescriptors();
    }

    /**
     * Create an instance of {@link AudioMapDescriptors }
     * 
     */
    public AudioMapDescriptors createAudioMapDescriptors() {
        return new AudioMapDescriptors();
    }

    /**
     * Create an instance of {@link ExternalPortDescriptors }
     * 
     */
    public ExternalPortDescriptors createExternalPortDescriptors() {
        return new ExternalPortDescriptors();
    }

    /**
     * Create an instance of {@link SignalSplitterDescriptor }
     * 
     */
    public SignalSplitterDescriptor createSignalSplitterDescriptor() {
        return new SignalSplitterDescriptor();
    }

    /**
     * Create an instance of {@link InternalPortDescriptor }
     * 
     */
    public InternalPortDescriptor createInternalPortDescriptor() {
        return new InternalPortDescriptor();
    }

    /**
     * Create an instance of {@link StringsDescriptor }
     * 
     */
    public StringsDescriptor createStringsDescriptor() {
        return new StringsDescriptor();
    }

    /**
     * Create an instance of {@link MatrixDescriptors }
     * 
     */
    public MatrixDescriptors createMatrixDescriptors() {
        return new MatrixDescriptors();
    }

    /**
     * Create an instance of {@link LocalizedStringContainerOptions }
     * 
     */
    public LocalizedStringContainerOptions createLocalizedStringContainerOptions() {
        return new LocalizedStringContainerOptions();
    }

    /**
     * Create an instance of {@link VideoClusterFormatSpecifics }
     * 
     */
    public VideoClusterFormatSpecifics createVideoClusterFormatSpecifics() {
        return new VideoClusterFormatSpecifics();
    }

    /**
     * Create an instance of {@link ConfigurationDescriptor }
     * 
     */
    public ConfigurationDescriptor createConfigurationDescriptor() {
        return new ConfigurationDescriptor();
    }

    /**
     * Create an instance of {@link VideoClusterAspectRatios }
     * 
     */
    public VideoClusterAspectRatios createVideoClusterAspectRatios() {
        return new VideoClusterAspectRatios();
    }

    /**
     * Create an instance of {@link VideoStreamPortDescriptors }
     * 
     */
    public VideoStreamPortDescriptors createVideoStreamPortDescriptors() {
        return new VideoStreamPortDescriptors();
    }

    /**
     * Create an instance of {@link ControlBlockDescriptor }
     * 
     */
    public ControlBlockDescriptor createControlBlockDescriptor() {
        return new ControlBlockDescriptor();
    }

    /**
     * Create an instance of {@link CurrentUnsignedDoublets }
     * 
     */
    public CurrentUnsignedDoublets createCurrentUnsignedDoublets() {
        return new CurrentUnsignedDoublets();
    }

    /**
     * Create an instance of {@link SignalSplitterMapping }
     * 
     */
    public SignalSplitterMapping createSignalSplitterMapping() {
        return new SignalSplitterMapping();
    }

    /**
     * Create an instance of {@link SignalSplitterDescriptors }
     * 
     */
    public SignalSplitterDescriptors createSignalSplitterDescriptors() {
        return new SignalSplitterDescriptors();
    }

    /**
     * Create an instance of {@link SignalMultiplexerSignalSource }
     * 
     */
    public SignalMultiplexerSignalSource createSignalMultiplexerSignalSource() {
        return new SignalMultiplexerSignalSource();
    }

    /**
     * Create an instance of {@link SignedOctetOptions }
     * 
     */
    public SignedOctetOptions createSignedOctetOptions() {
        return new SignedOctetOptions();
    }

    /**
     * Create an instance of {@link MatrixDescriptor }
     * 
     */
    public MatrixDescriptor createMatrixDescriptor() {
        return new MatrixDescriptor();
    }

    /**
     * Create an instance of {@link VideoMapping }
     * 
     */
    public VideoMapping createVideoMapping() {
        return new VideoMapping();
    }

    /**
     * Create an instance of {@link VideoClusterColorSpaces }
     * 
     */
    public VideoClusterColorSpaces createVideoClusterColorSpaces() {
        return new VideoClusterColorSpaces();
    }

    /**
     * Create an instance of {@link SensorFormats }
     * 
     */
    public SensorFormats createSensorFormats() {
        return new SensorFormats();
    }

    /**
     * Create an instance of {@link SignalTranscoderDescriptor }
     * 
     */
    public SignalTranscoderDescriptor createSignalTranscoderDescriptor() {
        return new SignalTranscoderDescriptor();
    }

    /**
     * Create an instance of {@link ClockDomainDescriptors }
     * 
     */
    public ClockDomainDescriptors createClockDomainDescriptors() {
        return new ClockDomainDescriptors();
    }

    /**
     * Create an instance of {@link StreamFormats }
     * 
     */
    public StreamFormats createStreamFormats() {
        return new StreamFormats();
    }

    /**
     * Create an instance of {@link SignalSelectorSignalSources }
     * 
     */
    public SignalSelectorSignalSources createSignalSelectorSignalSources() {
        return new SignalSelectorSignalSources();
    }

    /**
     * Create an instance of {@link UnsignedOctletOptions }
     * 
     */
    public UnsignedOctletOptions createUnsignedOctletOptions() {
        return new UnsignedOctletOptions();
    }

    /**
     * Create an instance of {@link SignedQuadletOptions }
     * 
     */
    public SignedQuadletOptions createSignedQuadletOptions() {
        return new SignedQuadletOptions();
    }

    /**
     * Create an instance of {@link MatrixSignalSourceContent }
     * 
     */
    public MatrixSignalSourceContent createMatrixSignalSourceContent() {
        return new MatrixSignalSourceContent();
    }

    /**
     * Create an instance of {@link VideoUnitDescriptors }
     * 
     */
    public VideoUnitDescriptors createVideoUnitDescriptors() {
        return new VideoUnitDescriptors();
    }

    /**
     * Create an instance of {@link AVBInterfaceDescriptors }
     * 
     */
    public AVBInterfaceDescriptors createAVBInterfaceDescriptors() {
        return new AVBInterfaceDescriptors();
    }

    /**
     * Create an instance of {@link CurrentUnsignedOctlets }
     * 
     */
    public CurrentUnsignedOctlets createCurrentUnsignedOctlets() {
        return new CurrentUnsignedOctlets();
    }

    /**
     * Create an instance of {@link SignalDemultiplexerMappings }
     * 
     */
    public SignalDemultiplexerMappings createSignalDemultiplexerMappings() {
        return new SignalDemultiplexerMappings();
    }

    /**
     * Create an instance of {@link SensorClusterDescriptor }
     * 
     */
    public SensorClusterDescriptor createSensorClusterDescriptor() {
        return new SensorClusterDescriptor();
    }

    /**
     * Create an instance of {@link CurrentSignedOctets }
     * 
     */
    public CurrentSignedOctets createCurrentSignedOctets() {
        return new CurrentSignedOctets();
    }

    /**
     * Create an instance of {@link MatrixSignalSource }
     * 
     */
    public MatrixSignalSource createMatrixSignalSource() {
        return new MatrixSignalSource();
    }

    /**
     * Create an instance of {@link ClockSourceDescriptors }
     * 
     */
    public ClockSourceDescriptors createClockSourceDescriptors() {
        return new ClockSourceDescriptors();
    }

    /**
     * Create an instance of {@link SignalMultiplexerDescriptor }
     * 
     */
    public SignalMultiplexerDescriptor createSignalMultiplexerDescriptor() {
        return new SignalMultiplexerDescriptor();
    }

    /**
     * Create an instance of {@link JackDescriptor }
     * 
     */
    public JackDescriptor createJackDescriptor() {
        return new JackDescriptor();
    }

    /**
     * Create an instance of {@link SignedDoubletOptions }
     * 
     */
    public SignedDoubletOptions createSignedDoubletOptions() {
        return new SignedDoubletOptions();
    }

    /**
     * Create an instance of {@link StringsDescriptors }
     * 
     */
    public StringsDescriptors createStringsDescriptors() {
        return new StringsDescriptors();
    }

    /**
     * Create an instance of {@link SensorMapDescriptor }
     * 
     */
    public SensorMapDescriptor createSensorMapDescriptor() {
        return new SensorMapDescriptor();
    }

    /**
     * Create an instance of {@link SignalDemultiplexerMapping }
     * 
     */
    public SignalDemultiplexerMapping createSignalDemultiplexerMapping() {
        return new SignalDemultiplexerMapping();
    }

    /**
     * Create an instance of {@link JackDescriptors }
     * 
     */
    public JackDescriptors createJackDescriptors() {
        return new JackDescriptors();
    }

    /**
     * Create an instance of {@link AudioClusterDescriptor }
     * 
     */
    public AudioClusterDescriptor createAudioClusterDescriptor() {
        return new AudioClusterDescriptor();
    }

    /**
     * Create an instance of {@link AudioStreamPortDescriptors }
     * 
     */
    public AudioStreamPortDescriptors createAudioStreamPortDescriptors() {
        return new AudioStreamPortDescriptors();
    }

    /**
     * Create an instance of {@link VideoUnitDescriptor }
     * 
     */
    public VideoUnitDescriptor createVideoUnitDescriptor() {
        return new VideoUnitDescriptor();
    }

    /**
     * Create an instance of {@link ConfigurationDescriptors }
     * 
     */
    public ConfigurationDescriptors createConfigurationDescriptors() {
        return new ConfigurationDescriptors();
    }

    /**
     * Create an instance of {@link CurrentSignedQuadlets }
     * 
     */
    public CurrentSignedQuadlets createCurrentSignedQuadlets() {
        return new CurrentSignedQuadlets();
    }

    /**
     * Create an instance of {@link SignalMultiplexerSignalSources }
     * 
     */
    public SignalMultiplexerSignalSources createSignalMultiplexerSignalSources() {
        return new SignalMultiplexerSignalSources();
    }

    /**
     * Create an instance of {@link ClockSourceIndexes }
     * 
     */
    public ClockSourceIndexes createClockSourceIndexes() {
        return new ClockSourceIndexes();
    }

    /**
     * Create an instance of {@link StreamDescriptor }
     * 
     */
    public StreamDescriptor createStreamDescriptor() {
        return new StreamDescriptor();
    }

    /**
     * Create an instance of {@link AudioMapDescriptor }
     * 
     */
    public AudioMapDescriptor createAudioMapDescriptor() {
        return new AudioMapDescriptor();
    }

    /**
     * Create an instance of {@link MatrixSignalDescriptors }
     * 
     */
    public MatrixSignalDescriptors createMatrixSignalDescriptors() {
        return new MatrixSignalDescriptors();
    }

    /**
     * Create an instance of {@link CurrentUnsignedOctets }
     * 
     */
    public CurrentUnsignedOctets createCurrentUnsignedOctets() {
        return new CurrentUnsignedOctets();
    }

    /**
     * Create an instance of {@link SignalSelectorDescriptor }
     * 
     */
    public SignalSelectorDescriptor createSignalSelectorDescriptor() {
        return new SignalSelectorDescriptor();
    }

    /**
     * Create an instance of {@link ClockSourceDescriptor }
     * 
     */
    public ClockSourceDescriptor createClockSourceDescriptor() {
        return new ClockSourceDescriptor();
    }

    /**
     * Create an instance of {@link CurrentUnsignedQuadlets }
     * 
     */
    public CurrentUnsignedQuadlets createCurrentUnsignedQuadlets() {
        return new CurrentUnsignedQuadlets();
    }

    /**
     * Create an instance of {@link DoubleOptions }
     * 
     */
    public DoubleOptions createDoubleOptions() {
        return new DoubleOptions();
    }

    /**
     * Create an instance of {@link BodePlotList }
     * 
     */
    public BodePlotList createBodePlotList() {
        return new BodePlotList();
    }

    /**
     * Create an instance of {@link VideoSize }
     * 
     */
    public VideoSize createVideoSize() {
        return new VideoSize();
    }

    /**
     * Create an instance of {@link SignalMultiplexerSignalSourceMappings }
     * 
     */
    public SignalMultiplexerSignalSourceMappings createSignalMultiplexerSignalSourceMappings() {
        return new SignalMultiplexerSignalSourceMappings();
    }

    /**
     * Create an instance of {@link CurrentDoubles }
     * 
     */
    public CurrentDoubles createCurrentDoubles() {
        return new CurrentDoubles();
    }

    /**
     * Create an instance of {@link VideoClusterDescriptor }
     * 
     */
    public VideoClusterDescriptor createVideoClusterDescriptor() {
        return new VideoClusterDescriptor();
    }

    /**
     * Create an instance of {@link MatrixSignalDescriptor }
     * 
     */
    public MatrixSignalDescriptor createMatrixSignalDescriptor() {
        return new MatrixSignalDescriptor();
    }

    /**
     * Create an instance of {@link VideoStreamPortDescriptor }
     * 
     */
    public VideoStreamPortDescriptor createVideoStreamPortDescriptor() {
        return new VideoStreamPortDescriptor();
    }

    /**
     * Create an instance of {@link CurrentSignedOctlets }
     * 
     */
    public CurrentSignedOctlets createCurrentSignedOctlets() {
        return new CurrentSignedOctlets();
    }

    /**
     * Create an instance of {@link AudioClusterDescriptors }
     * 
     */
    public AudioClusterDescriptors createAudioClusterDescriptors() {
        return new AudioClusterDescriptors();
    }

    /**
     * Create an instance of {@link AudioUnitDescriptor }
     * 
     */
    public AudioUnitDescriptor createAudioUnitDescriptor() {
        return new AudioUnitDescriptor();
    }

    /**
     * Create an instance of {@link SignalTranscoderDescriptors }
     * 
     */
    public SignalTranscoderDescriptors createSignalTranscoderDescriptors() {
        return new SignalTranscoderDescriptors();
    }

    /**
     * Create an instance of {@link ControlDescriptor }
     * 
     */
    public ControlDescriptor createControlDescriptor() {
        return new ControlDescriptor();
    }

    /**
     * Create an instance of {@link ControlBlockDescriptors }
     * 
     */
    public ControlBlockDescriptors createControlBlockDescriptors() {
        return new ControlBlockDescriptors();
    }

    /**
     * Create an instance of {@link MixerDescriptors }
     * 
     */
    public MixerDescriptors createMixerDescriptors() {
        return new MixerDescriptors();
    }

    /**
     * Create an instance of {@link AudioUnitDescriptors }
     * 
     */
    public AudioUnitDescriptors createAudioUnitDescriptors() {
        return new AudioUnitDescriptors();
    }

    /**
     * Create an instance of {@link BodePlotPoint }
     * 
     */
    public BodePlotPoint createBodePlotPoint() {
        return new BodePlotPoint();
    }

    /**
     * Create an instance of {@link AspectRatio }
     * 
     */
    public AspectRatio createAspectRatio() {
        return new AspectRatio();
    }

    /**
     * Create an instance of {@link VideoMapDescriptor }
     * 
     */
    public VideoMapDescriptor createVideoMapDescriptor() {
        return new VideoMapDescriptor();
    }

    /**
     * Create an instance of {@link SamplingRate }
     * 
     */
    public SamplingRate createSamplingRate() {
        return new SamplingRate();
    }

    /**
     * Create an instance of {@link SignalCombinerDescriptor }
     * 
     */
    public SignalCombinerDescriptor createSignalCombinerDescriptor() {
        return new SignalCombinerDescriptor();
    }

    /**
     * Create an instance of {@link SignalCombinerSource }
     * 
     */
    public SignalCombinerSource createSignalCombinerSource() {
        return new SignalCombinerSource();
    }

    /**
     * Create an instance of {@link FloatOptions }
     * 
     */
    public FloatOptions createFloatOptions() {
        return new FloatOptions();
    }

    /**
     * Create an instance of {@link T0015 }
     * 
     */
    public T0015 createT0015() {
        return new T0015();
    }

    /**
     * Create an instance of {@link T0016 }
     * 
     */
    public T0016 createT0016() {
        return new T0016();
    }

    /**
     * Create an instance of {@link SensorStreamPortDescriptor }
     * 
     */
    public SensorStreamPortDescriptor createSensorStreamPortDescriptor() {
        return new SensorStreamPortDescriptor();
    }

    /**
     * Create an instance of {@link T0017 }
     * 
     */
    public T0017 createT0017() {
        return new T0017();
    }

    /**
     * Create an instance of {@link T0018 }
     * 
     */
    public T0018 createT0018() {
        return new T0018();
    }

    /**
     * Create an instance of {@link T0019 }
     * 
     */
    public T0019 createT0019() {
        return new T0019();
    }

    /**
     * Create an instance of {@link ExternalPortDescriptor }
     * 
     */
    public ExternalPortDescriptor createExternalPortDescriptor() {
        return new ExternalPortDescriptor();
    }

    /**
     * Create an instance of {@link MixerDescriptor }
     * 
     */
    public MixerDescriptor createMixerDescriptor() {
        return new MixerDescriptor();
    }

    /**
     * Create an instance of {@link SignalCombinerMapping }
     * 
     */
    public SignalCombinerMapping createSignalCombinerMapping() {
        return new SignalCombinerMapping();
    }

    /**
     * Create an instance of {@link LocalizedStringContainer }
     * 
     */
    public LocalizedStringContainer createLocalizedStringContainer() {
        return new LocalizedStringContainer();
    }

    /**
     * Create an instance of {@link UnsignedDoubletOptions }
     * 
     */
    public UnsignedDoubletOptions createUnsignedDoubletOptions() {
        return new UnsignedDoubletOptions();
    }

    /**
     * Create an instance of {@link T0010 }
     * 
     */
    public T0010 createT0010() {
        return new T0010();
    }

    /**
     * Create an instance of {@link SignalDemultiplexerDescriptor }
     * 
     */
    public SignalDemultiplexerDescriptor createSignalDemultiplexerDescriptor() {
        return new SignalDemultiplexerDescriptor();
    }

    /**
     * Create an instance of {@link T0011 }
     * 
     */
    public T0011 createT0011() {
        return new T0011();
    }

    /**
     * Create an instance of {@link CurrentFloats }
     * 
     */
    public CurrentFloats createCurrentFloats() {
        return new CurrentFloats();
    }

    /**
     * Create an instance of {@link T0012 }
     * 
     */
    public T0012 createT0012() {
        return new T0012();
    }

    /**
     * Create an instance of {@link T0013 }
     * 
     */
    public T0013 createT0013() {
        return new T0013();
    }

    /**
     * Create an instance of {@link SignalSplitterMappings }
     * 
     */
    public SignalSplitterMappings createSignalSplitterMappings() {
        return new SignalSplitterMappings();
    }

    /**
     * Create an instance of {@link T0014 }
     * 
     */
    public T0014 createT0014() {
        return new T0014();
    }

    /**
     * Create an instance of {@link AudioMapping }
     * 
     */
    public AudioMapping createAudioMapping() {
        return new AudioMapping();
    }

    /**
     * Create an instance of {@link StreamDescriptors }
     * 
     */
    public StreamDescriptors createStreamDescriptors() {
        return new StreamDescriptors();
    }

    /**
     * Create an instance of {@link SignalCombinerSources }
     * 
     */
    public SignalCombinerSources createSignalCombinerSources() {
        return new SignalCombinerSources();
    }

    /**
     * Create an instance of {@link LocalizedString }
     * 
     */
    public LocalizedString createLocalizedString() {
        return new LocalizedString();
    }

    /**
     * Create an instance of {@link CurrentSignedDoublets }
     * 
     */
    public CurrentSignedDoublets createCurrentSignedDoublets() {
        return new CurrentSignedDoublets();
    }

    /**
     * Create an instance of {@link SignedOctletOptions }
     * 
     */
    public SignedOctletOptions createSignedOctletOptions() {
        return new SignedOctletOptions();
    }

    /**
     * Create an instance of {@link T3Ffe }
     * 
     */
    public T3Ffe createT3Ffe() {
        return new T3Ffe();
    }

    /**
     * Create an instance of {@link SignalCombinerDescriptors }
     * 
     */
    public SignalCombinerDescriptors createSignalCombinerDescriptors() {
        return new SignalCombinerDescriptors();
    }

    /**
     * Create an instance of {@link T0006 }
     * 
     */
    public T0006 createT0006() {
        return new T0006();
    }

    /**
     * Create an instance of {@link AVBInterfaceDescriptor }
     * 
     */
    public AVBInterfaceDescriptor createAVBInterfaceDescriptor() {
        return new AVBInterfaceDescriptor();
    }

    /**
     * Create an instance of {@link T0007 }
     * 
     */
    public T0007 createT0007() {
        return new T0007();
    }

    /**
     * Create an instance of {@link BodePlot }
     * 
     */
    public BodePlot createBodePlot() {
        return new BodePlot();
    }

    /**
     * Create an instance of {@link T0004 }
     * 
     */
    public T0004 createT0004() {
        return new T0004();
    }

    /**
     * Create an instance of {@link T0005 }
     * 
     */
    public T0005 createT0005() {
        return new T0005();
    }

    /**
     * Create an instance of {@link MixerSignalSource }
     * 
     */
    public MixerSignalSource createMixerSignalSource() {
        return new MixerSignalSource();
    }

    /**
     * Create an instance of {@link SignalCombinerMappings }
     * 
     */
    public SignalCombinerMappings createSignalCombinerMappings() {
        return new SignalCombinerMappings();
    }

    /**
     * Create an instance of {@link VideoClusterSizes }
     * 
     */
    public VideoClusterSizes createVideoClusterSizes() {
        return new VideoClusterSizes();
    }

    /**
     * Create an instance of {@link SensorMapping }
     * 
     */
    public SensorMapping createSensorMapping() {
        return new SensorMapping();
    }

    /**
     * Create an instance of {@link MemoryObjectDescriptor }
     * 
     */
    public MemoryObjectDescriptor createMemoryObjectDescriptor() {
        return new MemoryObjectDescriptor();
    }

    /**
     * Create an instance of {@link T0008 }
     * 
     */
    public T0008 createT0008() {
        return new T0008();
    }

    /**
     * Create an instance of {@link MixerSignalSources }
     * 
     */
    public MixerSignalSources createMixerSignalSources() {
        return new MixerSignalSources();
    }

    /**
     * Create an instance of {@link T0009 }
     * 
     */
    public T0009 createT0009() {
        return new T0009();
    }

    /**
     * Create an instance of {@link UnsignedOctetOptions }
     * 
     */
    public UnsignedOctetOptions createUnsignedOctetOptions() {
        return new UnsignedOctetOptions();
    }

    /**
     * Create an instance of {@link T0002 }
     * 
     */
    public T0002 createT0002() {
        return new T0002();
    }

    /**
     * Create an instance of {@link SignalSelectorSignalSource }
     * 
     */
    public SignalSelectorSignalSource createSignalSelectorSignalSource() {
        return new SignalSelectorSignalSource();
    }

    /**
     * Create an instance of {@link T0003 }
     * 
     */
    public T0003 createT0003() {
        return new T0003();
    }

    /**
     * Create an instance of {@link LocaleDescriptor }
     * 
     */
    public LocaleDescriptor createLocaleDescriptor() {
        return new LocaleDescriptor();
    }

    /**
     * Create an instance of {@link T0000 }
     * 
     */
    public T0000 createT0000() {
        return new T0000();
    }

    /**
     * Create an instance of {@link T0001 }
     * 
     */
    public T0001 createT0001() {
        return new T0001();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EntityV1 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://grouper.ieee.org/groups/1722/1/contributions/xml", name = "entity")
    public JAXBElement<EntityV1> createEntity(EntityV1 value) {
        return new JAXBElement<EntityV1>(_Entity_QNAME, EntityV1 .class, null, value);
    }

}
