//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.31 at 08:56:32 PM PDT 
//


package com.jdkoftinoff.jdksavdecc.aemxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * See IEEE Std 1722.1-2013 Clause 7.2.21
 * 
 * <p>Java class for SensorMapping complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SensorMapping">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="stream_index" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}DescriptorIndex"/>
 *         &lt;element name="stream_signal" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Doublet"/>
 *         &lt;element name="cluster_offset" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Doublet"/>
 *       &lt;/sequence>
 *       &lt;attribute name="symbol" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SensorMapping", propOrder = {
    "streamIndex",
    "streamSignal",
    "clusterOffset"
})
public class SensorMapping {

    @XmlElement(name = "stream_index", required = true)
    protected String streamIndex;
    @XmlElement(name = "stream_signal", required = true)
    protected String streamSignal;
    @XmlElement(name = "cluster_offset", required = true)
    protected String clusterOffset;
    @XmlAttribute(name = "symbol")
    protected String symbol;

    /**
     * Gets the value of the streamIndex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreamIndex() {
        return streamIndex;
    }

    /**
     * Sets the value of the streamIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreamIndex(String value) {
        this.streamIndex = value;
    }

    /**
     * Gets the value of the streamSignal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreamSignal() {
        return streamSignal;
    }

    /**
     * Sets the value of the streamSignal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreamSignal(String value) {
        this.streamSignal = value;
    }

    /**
     * Gets the value of the clusterOffset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClusterOffset() {
        return clusterOffset;
    }

    /**
     * Sets the value of the clusterOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClusterOffset(String value) {
        this.clusterOffset = value;
    }

    /**
     * Gets the value of the symbol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * Sets the value of the symbol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSymbol(String value) {
        this.symbol = value;
    }

}
