//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.31 at 08:56:32 PM PDT 
//


package com.jdkoftinoff.jdksavdecc.aemxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * See IEEE Std 1722.1-2013 Clause 7.2.27
 * 
 * <p>Java class for SignalSplitterDescriptor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SignalSplitterDescriptor">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="object_name" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}AVDECCString" minOccurs="0"/>
 *         &lt;element name="localized_description" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}LocalizedStringContainer"/>
 *         &lt;element name="block_latency" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Quadlet"/>
 *         &lt;element name="control_latency" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Quadlet"/>
 *         &lt;element name="control_domain" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}DescriptorIndex"/>
 *         &lt;element name="signal_type" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}DescriptorType"/>
 *         &lt;element name="signal_index" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}DescriptorIndex"/>
 *         &lt;element name="signal_output" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Doublet"/>
 *         &lt;element name="number_of_outputs" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Doublet"/>
 *         &lt;element name="mapping" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}SignalSplitterMappings"/>
 *       &lt;/sequence>
 *       &lt;attribute name="symbol" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SignalSplitterDescriptor", propOrder = {
    "objectName",
    "localizedDescription",
    "blockLatency",
    "controlLatency",
    "controlDomain",
    "signalType",
    "signalIndex",
    "signalOutput",
    "numberOfOutputs",
    "mapping"
})
public class SignalSplitterDescriptor {

    @XmlElement(name = "object_name")
    protected String objectName;
    @XmlElement(name = "localized_description", required = true)
    protected LocalizedStringContainer localizedDescription;
    @XmlElement(name = "block_latency", required = true)
    protected String blockLatency;
    @XmlElement(name = "control_latency", required = true)
    protected String controlLatency;
    @XmlElement(name = "control_domain", required = true)
    protected String controlDomain;
    @XmlElement(name = "signal_type", required = true)
    protected String signalType;
    @XmlElement(name = "signal_index", required = true)
    protected String signalIndex;
    @XmlElement(name = "signal_output", required = true)
    protected String signalOutput;
    @XmlElement(name = "number_of_outputs", required = true)
    protected String numberOfOutputs;
    @XmlElement(required = true)
    protected SignalSplitterMappings mapping;
    @XmlAttribute(name = "symbol")
    protected String symbol;

    /**
     * Gets the value of the objectName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjectName() {
        return objectName;
    }

    /**
     * Sets the value of the objectName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjectName(String value) {
        this.objectName = value;
    }

    /**
     * Gets the value of the localizedDescription property.
     * 
     * @return
     *     possible object is
     *     {@link LocalizedStringContainer }
     *     
     */
    public LocalizedStringContainer getLocalizedDescription() {
        return localizedDescription;
    }

    /**
     * Sets the value of the localizedDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocalizedStringContainer }
     *     
     */
    public void setLocalizedDescription(LocalizedStringContainer value) {
        this.localizedDescription = value;
    }

    /**
     * Gets the value of the blockLatency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlockLatency() {
        return blockLatency;
    }

    /**
     * Sets the value of the blockLatency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlockLatency(String value) {
        this.blockLatency = value;
    }

    /**
     * Gets the value of the controlLatency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getControlLatency() {
        return controlLatency;
    }

    /**
     * Sets the value of the controlLatency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setControlLatency(String value) {
        this.controlLatency = value;
    }

    /**
     * Gets the value of the controlDomain property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getControlDomain() {
        return controlDomain;
    }

    /**
     * Sets the value of the controlDomain property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setControlDomain(String value) {
        this.controlDomain = value;
    }

    /**
     * Gets the value of the signalType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignalType() {
        return signalType;
    }

    /**
     * Sets the value of the signalType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignalType(String value) {
        this.signalType = value;
    }

    /**
     * Gets the value of the signalIndex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignalIndex() {
        return signalIndex;
    }

    /**
     * Sets the value of the signalIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignalIndex(String value) {
        this.signalIndex = value;
    }

    /**
     * Gets the value of the signalOutput property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignalOutput() {
        return signalOutput;
    }

    /**
     * Sets the value of the signalOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignalOutput(String value) {
        this.signalOutput = value;
    }

    /**
     * Gets the value of the numberOfOutputs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOfOutputs() {
        return numberOfOutputs;
    }

    /**
     * Sets the value of the numberOfOutputs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOfOutputs(String value) {
        this.numberOfOutputs = value;
    }

    /**
     * Gets the value of the mapping property.
     * 
     * @return
     *     possible object is
     *     {@link SignalSplitterMappings }
     *     
     */
    public SignalSplitterMappings getMapping() {
        return mapping;
    }

    /**
     * Sets the value of the mapping property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignalSplitterMappings }
     *     
     */
    public void setMapping(SignalSplitterMappings value) {
        this.mapping = value;
    }

    /**
     * Gets the value of the symbol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * Sets the value of the symbol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSymbol(String value) {
        this.symbol = value;
    }

}
