//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.31 at 08:56:32 PM PDT 
//


package com.jdkoftinoff.jdksavdecc.aemxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * See IEEE Std 1722.1-2013 Clause 7.2.28
 * 
 * <p>Java class for SignalCombinerDescriptor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SignalCombinerDescriptor">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="object_name" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}AVDECCString" minOccurs="0"/>
 *         &lt;element name="localized_description" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}LocalizedStringContainer"/>
 *         &lt;element name="block_latency" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Quadlet"/>
 *         &lt;element name="control_latency" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Quadlet"/>
 *         &lt;element name="control_domain" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}DescriptorIndex"/>
 *         &lt;element name="sources" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}SignalCombinerSources"/>
 *         &lt;element name="mapping" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}SignalCombinerMappings"/>
 *       &lt;/sequence>
 *       &lt;attribute name="symbol" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SignalCombinerDescriptor", propOrder = {
    "objectName",
    "localizedDescription",
    "blockLatency",
    "controlLatency",
    "controlDomain",
    "sources",
    "mapping"
})
public class SignalCombinerDescriptor {

    @XmlElement(name = "object_name")
    protected String objectName;
    @XmlElement(name = "localized_description", required = true)
    protected LocalizedStringContainer localizedDescription;
    @XmlElement(name = "block_latency", required = true)
    protected String blockLatency;
    @XmlElement(name = "control_latency", required = true)
    protected String controlLatency;
    @XmlElement(name = "control_domain", required = true)
    protected String controlDomain;
    @XmlElement(required = true)
    protected SignalCombinerSources sources;
    @XmlElement(required = true)
    protected SignalCombinerMappings mapping;
    @XmlAttribute(name = "symbol")
    protected String symbol;

    /**
     * Gets the value of the objectName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjectName() {
        return objectName;
    }

    /**
     * Sets the value of the objectName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjectName(String value) {
        this.objectName = value;
    }

    /**
     * Gets the value of the localizedDescription property.
     * 
     * @return
     *     possible object is
     *     {@link LocalizedStringContainer }
     *     
     */
    public LocalizedStringContainer getLocalizedDescription() {
        return localizedDescription;
    }

    /**
     * Sets the value of the localizedDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocalizedStringContainer }
     *     
     */
    public void setLocalizedDescription(LocalizedStringContainer value) {
        this.localizedDescription = value;
    }

    /**
     * Gets the value of the blockLatency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlockLatency() {
        return blockLatency;
    }

    /**
     * Sets the value of the blockLatency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlockLatency(String value) {
        this.blockLatency = value;
    }

    /**
     * Gets the value of the controlLatency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getControlLatency() {
        return controlLatency;
    }

    /**
     * Sets the value of the controlLatency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setControlLatency(String value) {
        this.controlLatency = value;
    }

    /**
     * Gets the value of the controlDomain property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getControlDomain() {
        return controlDomain;
    }

    /**
     * Sets the value of the controlDomain property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setControlDomain(String value) {
        this.controlDomain = value;
    }

    /**
     * Gets the value of the sources property.
     * 
     * @return
     *     possible object is
     *     {@link SignalCombinerSources }
     *     
     */
    public SignalCombinerSources getSources() {
        return sources;
    }

    /**
     * Sets the value of the sources property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignalCombinerSources }
     *     
     */
    public void setSources(SignalCombinerSources value) {
        this.sources = value;
    }

    /**
     * Gets the value of the mapping property.
     * 
     * @return
     *     possible object is
     *     {@link SignalCombinerMappings }
     *     
     */
    public SignalCombinerMappings getMapping() {
        return mapping;
    }

    /**
     * Sets the value of the mapping property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignalCombinerMappings }
     *     
     */
    public void setMapping(SignalCombinerMappings value) {
        this.mapping = value;
    }

    /**
     * Gets the value of the symbol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * Sets the value of the symbol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSymbol(String value) {
        this.symbol = value;
    }

}
