//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.31 at 08:56:32 PM PDT 
//


package com.jdkoftinoff.jdksavdecc.aemxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SignalSelectorSignalSource complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SignalSelectorSignalSource">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="signal_type" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}DescriptorType"/>
 *         &lt;element name="signal_index" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}DescriptorIndex"/>
 *         &lt;element name="signal_output" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Doublet"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SignalSelectorSignalSource", propOrder = {
    "signalType",
    "signalIndex",
    "signalOutput"
})
public class SignalSelectorSignalSource {

    @XmlElement(name = "signal_type", required = true)
    protected String signalType;
    @XmlElement(name = "signal_index", required = true)
    protected String signalIndex;
    @XmlElement(name = "signal_output", required = true)
    protected String signalOutput;

    /**
     * Gets the value of the signalType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignalType() {
        return signalType;
    }

    /**
     * Sets the value of the signalType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignalType(String value) {
        this.signalType = value;
    }

    /**
     * Gets the value of the signalIndex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignalIndex() {
        return signalIndex;
    }

    /**
     * Sets the value of the signalIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignalIndex(String value) {
        this.signalIndex = value;
    }

    /**
     * Gets the value of the signalOutput property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignalOutput() {
        return signalOutput;
    }

    /**
     * Sets the value of the signalOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignalOutput(String value) {
        this.signalOutput = value;
    }

}
