//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.31 at 08:56:32 PM PDT 
//


package com.jdkoftinoff.jdksavdecc.aemxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * See IEEE Std 1722.1-2013 Clause 7.2.6
 * 
 * <p>Java class for StreamDescriptor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StreamDescriptor">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="object_name" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}AVDECCString" minOccurs="0"/>
 *         &lt;element name="localized_description" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}LocalizedStringContainer"/>
 *         &lt;element name="clock_domain_index" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}DescriptorIndex"/>
 *         &lt;element name="stream_flags" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Doublet"/>
 *         &lt;element name="current_stream_format" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}StreamFormat"/>
 *         &lt;element name="backup_talker_entity_id0" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}EUI64"/>
 *         &lt;element name="backup_talker_uniqueid0" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Doublet"/>
 *         &lt;element name="backup_talker_entity_id1" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}EUI64"/>
 *         &lt;element name="backup_talker_uniqueid1" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Doublet"/>
 *         &lt;element name="backup_talker_entity_id2" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}EUI64"/>
 *         &lt;element name="backup_talker_uniqueid2" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Doublet"/>
 *         &lt;element name="backed_up_talker_entity_id" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}EUI64"/>
 *         &lt;element name="backed_up_talker_uniqueid" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Doublet"/>
 *         &lt;element name="avb_interface_index" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}DescriptorIndex"/>
 *         &lt;element name="buffer_length" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Quadlet"/>
 *         &lt;element name="stream_formats" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}StreamFormats"/>
 *       &lt;/sequence>
 *       &lt;attribute name="symbol" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StreamDescriptor", propOrder = {
    "objectName",
    "localizedDescription",
    "clockDomainIndex",
    "streamFlags",
    "currentStreamFormat",
    "backupTalkerEntityId0",
    "backupTalkerUniqueid0",
    "backupTalkerEntityId1",
    "backupTalkerUniqueid1",
    "backupTalkerEntityId2",
    "backupTalkerUniqueid2",
    "backedUpTalkerEntityId",
    "backedUpTalkerUniqueid",
    "avbInterfaceIndex",
    "bufferLength",
    "streamFormats"
})
public class StreamDescriptor {

    @XmlElement(name = "object_name")
    protected String objectName;
    @XmlElement(name = "localized_description", required = true)
    protected LocalizedStringContainer localizedDescription;
    @XmlElement(name = "clock_domain_index", required = true)
    protected String clockDomainIndex;
    @XmlElement(name = "stream_flags", required = true)
    protected String streamFlags;
    @XmlElement(name = "current_stream_format", required = true)
    protected String currentStreamFormat;
    @XmlElement(name = "backup_talker_entity_id0", required = true)
    protected String backupTalkerEntityId0;
    @XmlElement(name = "backup_talker_uniqueid0", required = true)
    protected String backupTalkerUniqueid0;
    @XmlElement(name = "backup_talker_entity_id1", required = true)
    protected String backupTalkerEntityId1;
    @XmlElement(name = "backup_talker_uniqueid1", required = true)
    protected String backupTalkerUniqueid1;
    @XmlElement(name = "backup_talker_entity_id2", required = true)
    protected String backupTalkerEntityId2;
    @XmlElement(name = "backup_talker_uniqueid2", required = true)
    protected String backupTalkerUniqueid2;
    @XmlElement(name = "backed_up_talker_entity_id", required = true)
    protected String backedUpTalkerEntityId;
    @XmlElement(name = "backed_up_talker_uniqueid", required = true)
    protected String backedUpTalkerUniqueid;
    @XmlElement(name = "avb_interface_index", required = true)
    protected String avbInterfaceIndex;
    @XmlElement(name = "buffer_length", required = true)
    protected String bufferLength;
    @XmlElement(name = "stream_formats", required = true)
    protected StreamFormats streamFormats;
    @XmlAttribute(name = "symbol")
    protected String symbol;

    /**
     * Gets the value of the objectName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjectName() {
        return objectName;
    }

    /**
     * Sets the value of the objectName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjectName(String value) {
        this.objectName = value;
    }

    /**
     * Gets the value of the localizedDescription property.
     * 
     * @return
     *     possible object is
     *     {@link LocalizedStringContainer }
     *     
     */
    public LocalizedStringContainer getLocalizedDescription() {
        return localizedDescription;
    }

    /**
     * Sets the value of the localizedDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocalizedStringContainer }
     *     
     */
    public void setLocalizedDescription(LocalizedStringContainer value) {
        this.localizedDescription = value;
    }

    /**
     * Gets the value of the clockDomainIndex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClockDomainIndex() {
        return clockDomainIndex;
    }

    /**
     * Sets the value of the clockDomainIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClockDomainIndex(String value) {
        this.clockDomainIndex = value;
    }

    /**
     * Gets the value of the streamFlags property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreamFlags() {
        return streamFlags;
    }

    /**
     * Sets the value of the streamFlags property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreamFlags(String value) {
        this.streamFlags = value;
    }

    /**
     * Gets the value of the currentStreamFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentStreamFormat() {
        return currentStreamFormat;
    }

    /**
     * Sets the value of the currentStreamFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentStreamFormat(String value) {
        this.currentStreamFormat = value;
    }

    /**
     * Gets the value of the backupTalkerEntityId0 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackupTalkerEntityId0() {
        return backupTalkerEntityId0;
    }

    /**
     * Sets the value of the backupTalkerEntityId0 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackupTalkerEntityId0(String value) {
        this.backupTalkerEntityId0 = value;
    }

    /**
     * Gets the value of the backupTalkerUniqueid0 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackupTalkerUniqueid0() {
        return backupTalkerUniqueid0;
    }

    /**
     * Sets the value of the backupTalkerUniqueid0 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackupTalkerUniqueid0(String value) {
        this.backupTalkerUniqueid0 = value;
    }

    /**
     * Gets the value of the backupTalkerEntityId1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackupTalkerEntityId1() {
        return backupTalkerEntityId1;
    }

    /**
     * Sets the value of the backupTalkerEntityId1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackupTalkerEntityId1(String value) {
        this.backupTalkerEntityId1 = value;
    }

    /**
     * Gets the value of the backupTalkerUniqueid1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackupTalkerUniqueid1() {
        return backupTalkerUniqueid1;
    }

    /**
     * Sets the value of the backupTalkerUniqueid1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackupTalkerUniqueid1(String value) {
        this.backupTalkerUniqueid1 = value;
    }

    /**
     * Gets the value of the backupTalkerEntityId2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackupTalkerEntityId2() {
        return backupTalkerEntityId2;
    }

    /**
     * Sets the value of the backupTalkerEntityId2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackupTalkerEntityId2(String value) {
        this.backupTalkerEntityId2 = value;
    }

    /**
     * Gets the value of the backupTalkerUniqueid2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackupTalkerUniqueid2() {
        return backupTalkerUniqueid2;
    }

    /**
     * Sets the value of the backupTalkerUniqueid2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackupTalkerUniqueid2(String value) {
        this.backupTalkerUniqueid2 = value;
    }

    /**
     * Gets the value of the backedUpTalkerEntityId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackedUpTalkerEntityId() {
        return backedUpTalkerEntityId;
    }

    /**
     * Sets the value of the backedUpTalkerEntityId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackedUpTalkerEntityId(String value) {
        this.backedUpTalkerEntityId = value;
    }

    /**
     * Gets the value of the backedUpTalkerUniqueid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackedUpTalkerUniqueid() {
        return backedUpTalkerUniqueid;
    }

    /**
     * Sets the value of the backedUpTalkerUniqueid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackedUpTalkerUniqueid(String value) {
        this.backedUpTalkerUniqueid = value;
    }

    /**
     * Gets the value of the avbInterfaceIndex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvbInterfaceIndex() {
        return avbInterfaceIndex;
    }

    /**
     * Sets the value of the avbInterfaceIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvbInterfaceIndex(String value) {
        this.avbInterfaceIndex = value;
    }

    /**
     * Gets the value of the bufferLength property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBufferLength() {
        return bufferLength;
    }

    /**
     * Sets the value of the bufferLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBufferLength(String value) {
        this.bufferLength = value;
    }

    /**
     * Gets the value of the streamFormats property.
     * 
     * @return
     *     possible object is
     *     {@link StreamFormats }
     *     
     */
    public StreamFormats getStreamFormats() {
        return streamFormats;
    }

    /**
     * Sets the value of the streamFormats property.
     * 
     * @param value
     *     allowed object is
     *     {@link StreamFormats }
     *     
     */
    public void setStreamFormats(StreamFormats value) {
        this.streamFormats = value;
    }

    /**
     * Gets the value of the symbol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * Sets the value of the symbol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSymbol(String value) {
        this.symbol = value;
    }

}
