//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.31 at 08:56:32 PM PDT 
//


package com.jdkoftinoff.jdksavdecc.aemxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * See IEEE Std 1722.1-2013 Clause 7.3.5.2.6 - CONTROL_SMPTE_TIME
 * 
 * <p>Java class for T0021 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="T0021">
 *   &lt;complexContent>
 *     &lt;extension base="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Value">
 *       &lt;sequence>
 *         &lt;element name="hours" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Doublet"/>
 *         &lt;element name="minutes" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Octet"/>
 *         &lt;element name="seconds" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Octet"/>
 *         &lt;element name="frames" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Octet"/>
 *         &lt;element name="subframes" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Doublet"/>
 *         &lt;element name="frames_per_second" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Octet"/>
 *         &lt;element name="drop_frame" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Octet"/>
 *         &lt;element name="pull" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Octet"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "T0021", propOrder = {
    "hours",
    "minutes",
    "seconds",
    "frames",
    "subframes",
    "framesPerSecond",
    "dropFrame",
    "pull"
})
public class T0021
    extends Value
{

    @XmlElement(required = true)
    protected String hours;
    @XmlElement(required = true)
    protected String minutes;
    @XmlElement(required = true)
    protected String seconds;
    @XmlElement(required = true)
    protected String frames;
    @XmlElement(required = true)
    protected String subframes;
    @XmlElement(name = "frames_per_second", required = true)
    protected String framesPerSecond;
    @XmlElement(name = "drop_frame", required = true)
    protected String dropFrame;
    @XmlElement(required = true)
    protected String pull;

    /**
     * Gets the value of the hours property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHours() {
        return hours;
    }

    /**
     * Sets the value of the hours property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHours(String value) {
        this.hours = value;
    }

    /**
     * Gets the value of the minutes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinutes() {
        return minutes;
    }

    /**
     * Sets the value of the minutes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinutes(String value) {
        this.minutes = value;
    }

    /**
     * Gets the value of the seconds property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeconds() {
        return seconds;
    }

    /**
     * Sets the value of the seconds property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeconds(String value) {
        this.seconds = value;
    }

    /**
     * Gets the value of the frames property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrames() {
        return frames;
    }

    /**
     * Sets the value of the frames property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrames(String value) {
        this.frames = value;
    }

    /**
     * Gets the value of the subframes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubframes() {
        return subframes;
    }

    /**
     * Sets the value of the subframes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubframes(String value) {
        this.subframes = value;
    }

    /**
     * Gets the value of the framesPerSecond property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFramesPerSecond() {
        return framesPerSecond;
    }

    /**
     * Sets the value of the framesPerSecond property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFramesPerSecond(String value) {
        this.framesPerSecond = value;
    }

    /**
     * Gets the value of the dropFrame property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDropFrame() {
        return dropFrame;
    }

    /**
     * Sets the value of the dropFrame property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDropFrame(String value) {
        this.dropFrame = value;
    }

    /**
     * Gets the value of the pull property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPull() {
        return pull;
    }

    /**
     * Sets the value of the pull property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPull(String value) {
        this.pull = value;
    }

}
