//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.31 at 08:56:32 PM PDT 
//


package com.jdkoftinoff.jdksavdecc.aemxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * See IEEE Std 1722.1-2013 Clause 7.3.5.2.5 - CONTROL_BODE_PLOT
 * 
 * <p>Java class for T0020 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="T0020">
 *   &lt;complexContent>
 *     &lt;extension base="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Value">
 *       &lt;sequence>
 *         &lt;element name="minimum" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}BodePlotPoint"/>
 *         &lt;element name="maximum" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}BodePlotPoint"/>
 *         &lt;element name="step" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}BodePlotPoint"/>
 *         &lt;element name="default" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}BodePlotPoint"/>
 *         &lt;element name="current_values" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}BodePlotList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "T0020", propOrder = {
    "minimum",
    "maximum",
    "step",
    "_default",
    "currentValues"
})
public class T0020
    extends Value
{

    @XmlElement(required = true)
    protected BodePlotPoint minimum;
    @XmlElement(required = true)
    protected BodePlotPoint maximum;
    @XmlElement(required = true)
    protected BodePlotPoint step;
    @XmlElement(name = "default", required = true)
    protected BodePlotPoint _default;
    @XmlElement(name = "current_values")
    protected BodePlotList currentValues;

    /**
     * Gets the value of the minimum property.
     * 
     * @return
     *     possible object is
     *     {@link BodePlotPoint }
     *     
     */
    public BodePlotPoint getMinimum() {
        return minimum;
    }

    /**
     * Sets the value of the minimum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BodePlotPoint }
     *     
     */
    public void setMinimum(BodePlotPoint value) {
        this.minimum = value;
    }

    /**
     * Gets the value of the maximum property.
     * 
     * @return
     *     possible object is
     *     {@link BodePlotPoint }
     *     
     */
    public BodePlotPoint getMaximum() {
        return maximum;
    }

    /**
     * Sets the value of the maximum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BodePlotPoint }
     *     
     */
    public void setMaximum(BodePlotPoint value) {
        this.maximum = value;
    }

    /**
     * Gets the value of the step property.
     * 
     * @return
     *     possible object is
     *     {@link BodePlotPoint }
     *     
     */
    public BodePlotPoint getStep() {
        return step;
    }

    /**
     * Sets the value of the step property.
     * 
     * @param value
     *     allowed object is
     *     {@link BodePlotPoint }
     *     
     */
    public void setStep(BodePlotPoint value) {
        this.step = value;
    }

    /**
     * Gets the value of the default property.
     * 
     * @return
     *     possible object is
     *     {@link BodePlotPoint }
     *     
     */
    public BodePlotPoint getDefault() {
        return _default;
    }

    /**
     * Sets the value of the default property.
     * 
     * @param value
     *     allowed object is
     *     {@link BodePlotPoint }
     *     
     */
    public void setDefault(BodePlotPoint value) {
        this._default = value;
    }

    /**
     * Gets the value of the currentValues property.
     * 
     * @return
     *     possible object is
     *     {@link BodePlotList }
     *     
     */
    public BodePlotList getCurrentValues() {
        return currentValues;
    }

    /**
     * Sets the value of the currentValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link BodePlotList }
     *     
     */
    public void setCurrentValues(BodePlotList value) {
        this.currentValues = value;
    }

}
