//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.31 at 08:56:32 PM PDT 
//


package com.jdkoftinoff.jdksavdecc.aemxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * See IEEE Std 1722.1-2013 Clause 7.3.5.2.9 - CONTROL_VENDOR
 * 
 * <p>Java class for T3ffe complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="T3ffe">
 *   &lt;complexContent>
 *     &lt;extension base="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Value">
 *       &lt;sequence>
 *         &lt;element name="vendor_eui64" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}EUI64"/>
 *         &lt;element name="binary_blob" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}HexBlobData"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "T3ffe", propOrder = {
    "vendorEui64",
    "binaryBlob"
})
public class T3Ffe
    extends Value
{

    @XmlElement(name = "vendor_eui64", required = true)
    protected String vendorEui64;
    @XmlElement(name = "binary_blob", required = true)
    protected String binaryBlob;

    /**
     * Gets the value of the vendorEui64 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendorEui64() {
        return vendorEui64;
    }

    /**
     * Sets the value of the vendorEui64 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendorEui64(String value) {
        this.vendorEui64 = value;
    }

    /**
     * Gets the value of the binaryBlob property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBinaryBlob() {
        return binaryBlob;
    }

    /**
     * Sets the value of the binaryBlob property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBinaryBlob(String value) {
        this.binaryBlob = value;
    }

}
