//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.31 at 08:56:32 PM PDT 
//


package com.jdkoftinoff.jdksavdecc.aemxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * For value_type codes that do not match the standard set defined in IEEE Std 1722.1 Clause 7.3.5
 * 
 * <p>Java class for TUNKNOWN complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TUNKNOWN">
 *   &lt;complexContent>
 *     &lt;extension base="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Value">
 *       &lt;sequence>
 *         &lt;element name="binary_blob" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}HexBlobData"/>
 *       &lt;/sequence>
 *       &lt;attribute name="value_type" use="required" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Doublet" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TUNKNOWN", propOrder = {
    "binaryBlob"
})
public class TUNKNOWN
    extends Value
{

    @XmlElement(name = "binary_blob", required = true)
    protected String binaryBlob;
    @XmlAttribute(name = "value_type", required = true)
    protected String valueType;

    /**
     * Gets the value of the binaryBlob property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBinaryBlob() {
        return binaryBlob;
    }

    /**
     * Sets the value of the binaryBlob property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBinaryBlob(String value) {
        this.binaryBlob = value;
    }

    /**
     * Gets the value of the valueType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueType() {
        return valueType;
    }

    /**
     * Sets the value of the valueType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueType(String value) {
        this.valueType = value;
    }

}
