//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.31 at 08:56:32 PM PDT 
//


package com.jdkoftinoff.jdksavdecc.aemxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * See IEEE Std 1722.1-2013 Clause 7.3.5
 * 
 * <p>Java class for Value complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Value">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Value")
@XmlSeeAlso({
    T001A.class,
    T001B.class,
    T001C.class,
    T001D.class,
    TUNKNOWN.class,
    T001E.class,
    T001F.class,
    T000B.class,
    T000C.class,
    T000A.class,
    T000F.class,
    T000D.class,
    T000E.class,
    T0023 .class,
    T0022 .class,
    T0021 .class,
    T0020 .class,
    T0015 .class,
    T0016 .class,
    T0017 .class,
    T0018 .class,
    T0019 .class,
    T0010 .class,
    T0011 .class,
    T0012 .class,
    T0013 .class,
    T0014 .class,
    T3Ffe.class,
    T0006 .class,
    T0007 .class,
    T0004 .class,
    T0005 .class,
    T0008 .class,
    T0009 .class,
    T0002 .class,
    T0003 .class,
    T0000 .class,
    T0001 .class
})
public abstract class Value {


}
