//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.31 at 08:56:32 PM PDT 
//


package com.jdkoftinoff.jdksavdecc.aemxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VideoMapping complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VideoMapping">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="stream_index" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}DescriptorIndex"/>
 *         &lt;element name="program_stream" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Doublet"/>
 *         &lt;element name="elementary_stream" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Doublet"/>
 *         &lt;element name="cluster_offset" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Doublet"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VideoMapping", propOrder = {
    "streamIndex",
    "programStream",
    "elementaryStream",
    "clusterOffset"
})
public class VideoMapping {

    @XmlElement(name = "stream_index", required = true)
    protected String streamIndex;
    @XmlElement(name = "program_stream", required = true)
    protected String programStream;
    @XmlElement(name = "elementary_stream", required = true)
    protected String elementaryStream;
    @XmlElement(name = "cluster_offset", required = true)
    protected String clusterOffset;

    /**
     * Gets the value of the streamIndex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreamIndex() {
        return streamIndex;
    }

    /**
     * Sets the value of the streamIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreamIndex(String value) {
        this.streamIndex = value;
    }

    /**
     * Gets the value of the programStream property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProgramStream() {
        return programStream;
    }

    /**
     * Sets the value of the programStream property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProgramStream(String value) {
        this.programStream = value;
    }

    /**
     * Gets the value of the elementaryStream property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElementaryStream() {
        return elementaryStream;
    }

    /**
     * Sets the value of the elementaryStream property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElementaryStream(String value) {
        this.elementaryStream = value;
    }

    /**
     * Gets the value of the clusterOffset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClusterOffset() {
        return clusterOffset;
    }

    /**
     * Sets the value of the clusterOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClusterOffset(String value) {
        this.clusterOffset = value;
    }

}
