//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.31 at 08:56:32 PM PDT 
//


package com.jdkoftinoff.jdksavdecc.aemxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * See IEEE Std 1722.1-2013 Clause 7.2.17
 * 
 * <p>Java class for VideoClusterDescriptor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VideoClusterDescriptor">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="object_name" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}AVDECCString" minOccurs="0"/>
 *         &lt;element name="localized_description" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}LocalizedStringContainer"/>
 *         &lt;element name="signal_type" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}DescriptorType"/>
 *         &lt;element name="signal_index" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}DescriptorIndex"/>
 *         &lt;element name="signal_output" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Doublet"/>
 *         &lt;element name="path_latency" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Quadlet"/>
 *         &lt;element name="block_latency" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Quadlet"/>
 *         &lt;element name="format" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Octet"/>
 *         &lt;element name="current_format_specific" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}Quadlet"/>
 *         &lt;element name="current_sampling_rate" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}SamplingRate"/>
 *         &lt;element name="current_aspect_ratio" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}AspectRatio"/>
 *         &lt;element name="current_video_size" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}VideoSize"/>
 *         &lt;element name="current_color_space" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}ColorSpace"/>
 *         &lt;element name="format_specifics" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}VideoClusterFormatSpecifics"/>
 *         &lt;element name="sampling_rates" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}SamplingRates"/>
 *         &lt;element name="aspect_ratios" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}VideoClusterAspectRatios"/>
 *         &lt;element name="video_sizes" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}VideoClusterSizes"/>
 *         &lt;element name="color_spaces" type="{http://grouper.ieee.org/groups/1722/1/contributions/xml}VideoClusterColorSpaces"/>
 *       &lt;/sequence>
 *       &lt;attribute name="symbol" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VideoClusterDescriptor", propOrder = {
    "objectName",
    "localizedDescription",
    "signalType",
    "signalIndex",
    "signalOutput",
    "pathLatency",
    "blockLatency",
    "format",
    "currentFormatSpecific",
    "currentSamplingRate",
    "currentAspectRatio",
    "currentVideoSize",
    "currentColorSpace",
    "formatSpecifics",
    "samplingRates",
    "aspectRatios",
    "videoSizes",
    "colorSpaces"
})
public class VideoClusterDescriptor {

    @XmlElement(name = "object_name")
    protected String objectName;
    @XmlElement(name = "localized_description", required = true)
    protected LocalizedStringContainer localizedDescription;
    @XmlElement(name = "signal_type", required = true)
    protected String signalType;
    @XmlElement(name = "signal_index", required = true)
    protected String signalIndex;
    @XmlElement(name = "signal_output", required = true)
    protected String signalOutput;
    @XmlElement(name = "path_latency", required = true)
    protected String pathLatency;
    @XmlElement(name = "block_latency", required = true)
    protected String blockLatency;
    @XmlElement(required = true)
    protected String format;
    @XmlElement(name = "current_format_specific", required = true)
    protected String currentFormatSpecific;
    @XmlElement(name = "current_sampling_rate", required = true)
    protected SamplingRate currentSamplingRate;
    @XmlElement(name = "current_aspect_ratio", required = true)
    protected AspectRatio currentAspectRatio;
    @XmlElement(name = "current_video_size", required = true)
    protected VideoSize currentVideoSize;
    @XmlElement(name = "current_color_space", required = true)
    protected String currentColorSpace;
    @XmlElement(name = "format_specifics", required = true)
    protected VideoClusterFormatSpecifics formatSpecifics;
    @XmlElement(name = "sampling_rates", required = true)
    protected SamplingRates samplingRates;
    @XmlElement(name = "aspect_ratios", required = true)
    protected VideoClusterAspectRatios aspectRatios;
    @XmlElement(name = "video_sizes", required = true)
    protected VideoClusterSizes videoSizes;
    @XmlElement(name = "color_spaces", required = true)
    protected VideoClusterColorSpaces colorSpaces;
    @XmlAttribute(name = "symbol")
    protected String symbol;

    /**
     * Gets the value of the objectName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjectName() {
        return objectName;
    }

    /**
     * Sets the value of the objectName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjectName(String value) {
        this.objectName = value;
    }

    /**
     * Gets the value of the localizedDescription property.
     * 
     * @return
     *     possible object is
     *     {@link LocalizedStringContainer }
     *     
     */
    public LocalizedStringContainer getLocalizedDescription() {
        return localizedDescription;
    }

    /**
     * Sets the value of the localizedDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocalizedStringContainer }
     *     
     */
    public void setLocalizedDescription(LocalizedStringContainer value) {
        this.localizedDescription = value;
    }

    /**
     * Gets the value of the signalType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignalType() {
        return signalType;
    }

    /**
     * Sets the value of the signalType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignalType(String value) {
        this.signalType = value;
    }

    /**
     * Gets the value of the signalIndex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignalIndex() {
        return signalIndex;
    }

    /**
     * Sets the value of the signalIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignalIndex(String value) {
        this.signalIndex = value;
    }

    /**
     * Gets the value of the signalOutput property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignalOutput() {
        return signalOutput;
    }

    /**
     * Sets the value of the signalOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignalOutput(String value) {
        this.signalOutput = value;
    }

    /**
     * Gets the value of the pathLatency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPathLatency() {
        return pathLatency;
    }

    /**
     * Sets the value of the pathLatency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPathLatency(String value) {
        this.pathLatency = value;
    }

    /**
     * Gets the value of the blockLatency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlockLatency() {
        return blockLatency;
    }

    /**
     * Sets the value of the blockLatency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlockLatency(String value) {
        this.blockLatency = value;
    }

    /**
     * Gets the value of the format property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormat() {
        return format;
    }

    /**
     * Sets the value of the format property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormat(String value) {
        this.format = value;
    }

    /**
     * Gets the value of the currentFormatSpecific property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentFormatSpecific() {
        return currentFormatSpecific;
    }

    /**
     * Sets the value of the currentFormatSpecific property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentFormatSpecific(String value) {
        this.currentFormatSpecific = value;
    }

    /**
     * Gets the value of the currentSamplingRate property.
     * 
     * @return
     *     possible object is
     *     {@link SamplingRate }
     *     
     */
    public SamplingRate getCurrentSamplingRate() {
        return currentSamplingRate;
    }

    /**
     * Sets the value of the currentSamplingRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link SamplingRate }
     *     
     */
    public void setCurrentSamplingRate(SamplingRate value) {
        this.currentSamplingRate = value;
    }

    /**
     * Gets the value of the currentAspectRatio property.
     * 
     * @return
     *     possible object is
     *     {@link AspectRatio }
     *     
     */
    public AspectRatio getCurrentAspectRatio() {
        return currentAspectRatio;
    }

    /**
     * Sets the value of the currentAspectRatio property.
     * 
     * @param value
     *     allowed object is
     *     {@link AspectRatio }
     *     
     */
    public void setCurrentAspectRatio(AspectRatio value) {
        this.currentAspectRatio = value;
    }

    /**
     * Gets the value of the currentVideoSize property.
     * 
     * @return
     *     possible object is
     *     {@link VideoSize }
     *     
     */
    public VideoSize getCurrentVideoSize() {
        return currentVideoSize;
    }

    /**
     * Sets the value of the currentVideoSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link VideoSize }
     *     
     */
    public void setCurrentVideoSize(VideoSize value) {
        this.currentVideoSize = value;
    }

    /**
     * Gets the value of the currentColorSpace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentColorSpace() {
        return currentColorSpace;
    }

    /**
     * Sets the value of the currentColorSpace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentColorSpace(String value) {
        this.currentColorSpace = value;
    }

    /**
     * Gets the value of the formatSpecifics property.
     * 
     * @return
     *     possible object is
     *     {@link VideoClusterFormatSpecifics }
     *     
     */
    public VideoClusterFormatSpecifics getFormatSpecifics() {
        return formatSpecifics;
    }

    /**
     * Sets the value of the formatSpecifics property.
     * 
     * @param value
     *     allowed object is
     *     {@link VideoClusterFormatSpecifics }
     *     
     */
    public void setFormatSpecifics(VideoClusterFormatSpecifics value) {
        this.formatSpecifics = value;
    }

    /**
     * Gets the value of the samplingRates property.
     * 
     * @return
     *     possible object is
     *     {@link SamplingRates }
     *     
     */
    public SamplingRates getSamplingRates() {
        return samplingRates;
    }

    /**
     * Sets the value of the samplingRates property.
     * 
     * @param value
     *     allowed object is
     *     {@link SamplingRates }
     *     
     */
    public void setSamplingRates(SamplingRates value) {
        this.samplingRates = value;
    }

    /**
     * Gets the value of the aspectRatios property.
     * 
     * @return
     *     possible object is
     *     {@link VideoClusterAspectRatios }
     *     
     */
    public VideoClusterAspectRatios getAspectRatios() {
        return aspectRatios;
    }

    /**
     * Sets the value of the aspectRatios property.
     * 
     * @param value
     *     allowed object is
     *     {@link VideoClusterAspectRatios }
     *     
     */
    public void setAspectRatios(VideoClusterAspectRatios value) {
        this.aspectRatios = value;
    }

    /**
     * Gets the value of the videoSizes property.
     * 
     * @return
     *     possible object is
     *     {@link VideoClusterSizes }
     *     
     */
    public VideoClusterSizes getVideoSizes() {
        return videoSizes;
    }

    /**
     * Sets the value of the videoSizes property.
     * 
     * @param value
     *     allowed object is
     *     {@link VideoClusterSizes }
     *     
     */
    public void setVideoSizes(VideoClusterSizes value) {
        this.videoSizes = value;
    }

    /**
     * Gets the value of the colorSpaces property.
     * 
     * @return
     *     possible object is
     *     {@link VideoClusterColorSpaces }
     *     
     */
    public VideoClusterColorSpaces getColorSpaces() {
        return colorSpaces;
    }

    /**
     * Sets the value of the colorSpaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link VideoClusterColorSpaces }
     *     
     */
    public void setColorSpaces(VideoClusterColorSpaces value) {
        this.colorSpaces = value;
    }

    /**
     * Gets the value of the symbol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * Sets the value of the symbol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSymbol(String value) {
        this.symbol = value;
    }

}
